using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using FactoryManagmentSystem.Models;

namespace FactoryManagmentSystem.Views
{
    public partial class AddProductDialog : Window
    {
        public bool DialogResult { get; private set; } = false;
        public Product? NewProduct { get; private set; }

        public AddProductDialog()
        {
            InitializeComponent();
        }

        private void SaveButton_Click(object sender, RoutedEventArgs e)
        {
            if (ValidateForm())
            {
                // Create new product object based on category
                var selectedCategory = GetSelectedCategory();
                NewProduct = CreateProductByCategory(selectedCategory);

                if (NewProduct != null)
                {
                    PopulateProductData(NewProduct);
                    ShowDatabaseOperationMessage();
                    DialogResult = true;
                    this.Close();
                }
            }
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            this.Close();
        }

        private bool ValidateForm()
        {
            var errors = new System.Text.StringBuilder();

            if (string.IsNullOrWhiteSpace(ProductNameTextBox.Text))
                errors.AppendLine("• Product Name is required");

            if (string.IsNullOrWhiteSpace(SKUTextBox.Text))
                errors.AppendLine("• SKU is required");

            if (CategoryComboBox.SelectedItem == null)
                errors.AppendLine("• Category is required");

            if (string.IsNullOrWhiteSpace(PriceTextBox.Text))
                errors.AppendLine("• Sale Price is required");
            else if (!decimal.TryParse(PriceTextBox.Text, out decimal price) || price <= 0)
                errors.AppendLine("• Sale Price must be a valid positive number");

            if (MaterialComboBox.SelectedItem == null)
                errors.AppendLine("• Material is required");

            if (errors.Length > 0)
            {
                MessageBox.Show($"Please correct the following errors:\n\n{errors}", 
                    "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return false;
            }

            return true;
        }

        private ProductCategory GetSelectedCategory()
        {
            var selectedItem = (ComboBoxItem)CategoryComboBox.SelectedItem;
            var tagValue = selectedItem?.Tag?.ToString();
            
            if (Enum.TryParse<ProductCategory>(tagValue, out var category))
                return category;
            
            return ProductCategory.TShirts; // Default
        }

        private Product CreateProductByCategory(ProductCategory category)
        {
            // Create specific product type based on category
            return category switch
            {
                ProductCategory.TShirts => new TShirt(),
                ProductCategory.Shirts => new Shirt(),
                ProductCategory.Sweatshirts => new Sweatshirt(),
                ProductCategory.Pants => new Pants(),
                ProductCategory.Jeans => new Jeans(),
                ProductCategory.Jackets => new Jacket(),
                _ => new TShirt() // Default to T-Shirt
            };
        }

        private void PopulateProductData(Product product)
        {
            // Basic Information
            product.ProductId = 0; // Will be auto-generated by database
            // SKU is entered manually by user
            product.SKU = SKUTextBox.Text.Trim();
            product.Name = ProductNameTextBox.Text.Trim();
            product.Description = DescriptionTextBox.Text.Trim();
            product.Category = GetSelectedCategory();
            product.Brand = BrandTextBox.Text.Trim();

            // Pricing
            product.Price = decimal.Parse(PriceTextBox.Text);

            // Product Details
            product.Material = ((ComboBoxItem)MaterialComboBox.SelectedItem)?.Content?.ToString() ?? "";
            
            // Parse sizes and colors
            if (!string.IsNullOrWhiteSpace(SizesTextBox.Text))
            {
                var sizes = SizesTextBox.Text.Split(',')
                    .Select(s => s.Trim())
                    .Where(s => !string.IsNullOrEmpty(s))
                    .Select(s => Enum.TryParse<ProductSize>(s, true, out var size) ? size : ProductSize.M)
                    .ToList();
                product.AvailableSizes = sizes;
            }

            if (!string.IsNullOrWhiteSpace(ColorsTextBox.Text))
            {
                product.AvailableColors = ColorsTextBox.Text.Split(',')
                    .Select(c => c.Trim())
                    .Where(c => !string.IsNullOrEmpty(c))
                    .ToList();
            }

            // Additional Information
            product.CreatedDate = DateTime.Now;
            product.LastUpdated = DateTime.Now;
            product.IsActive = true;
            product.ProductionStatus = ProductionStatus.Ready; // Default to Ready
        }

        private void ShowDatabaseOperationMessage()
        {
            if (NewProduct == null) return;

            var sizesText = NewProduct.AvailableSizes.Any() ? string.Join(", ", NewProduct.AvailableSizes) : "Not specified";
            var colorsText = NewProduct.AvailableColors.Any() ? string.Join(", ", NewProduct.AvailableColors) : "Not specified";

            var message = $"✅ PRODUCT ADDED SUCCESSFULLY!\n\n" +
                         $"Product Details:\n" +
                         $"━━━━━━━━━━━━━━━━━━━━━━━━━━\n" +
                         $"📦 SKU: {NewProduct.SKU}\n" +
                         $"📝 Name: {NewProduct.Name}\n" +
                         $"🏷️ Category: {NewProduct.Category}\n" +
                         $"🏢 Brand: {NewProduct.Brand}\n" +
                         $"🧵 Material: {NewProduct.Material}\n" +
                         $"💰 Sale Price: ₨{NewProduct.Price:N2}\n" +
                         $"📏 Sizes: {sizesText}\n" +
                         $"🎨 Colors: {colorsText}\n\n" +
                         $"⚡ Product saved to database with unique SKU\n" +
                         $"📊 Now available in all modules and order forms";

            MessageBox.Show(message, "✅ Success - Product Added", 
                MessageBoxButton.OK, MessageBoxImage.Information);
        }
    }
}